<?php


namespace carono\yii2crud\actions;


use Closure;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\StringHelper;
use yii\web\NotFoundHttpException;

abstract class Action extends \yii\base\Action
{
    public $primaryKeyParam = ['id'];
    public $layout;
    public $view;
    public $modelClass;
    public $renderParams;
    public $findModel;
    protected $params = [];

    public function init()
    {
        if ($this->layout) {
            $this->controller->layout = $this->layout;
        }
        parent::init();
    }

    public function __call($name, $params)
    {
        if (StringHelper::startsWith($name, 'getMessage')) {
            $property = $this->{lcfirst(substr($name, 3))};
            if ($property instanceof \Closure) {
                return call_user_func_array($property, $params);
            }
            return $property;
        }
        return parent::__call($name, $params);
    }

    public function render($view, $params = [])
    {
        if ($this->renderParams instanceof \Closure) {
            $params = array_merge($params, call_user_func($this->renderParams, $params, $this));
        }
        if (is_array($this->renderParams)) {
            $params = array_merge($params, $this->renderParams);
        }
        return $this->controller->render($view, $params);
    }

    public function runWithParams($params)
    {
        $this->params = $params;
        return parent::runWithParams($params); // TODO: Change the autogenerated stub
    }

    public function getPrimaryKeys()
    {
        $ids = [];
        foreach ((array)$this->primaryKeyParam as $param => $field) {
            if (is_integer($param)) {
                $ids[$field] = ArrayHelper::getValue($this->params, $field);
            } else {
                $ids[$field] = ArrayHelper::getValue($this->params, $param);
            }
        }
        return $ids;
    }

    public function findModel($class)
    {
        $condition = [];
        foreach ($this->primaryKeyParam as $key) {
            $condition[$key] = $this->controller->request->get($key);
        }

        if (method_exists($this->controller, 'findModel')) {
            return $this->controller->findModel($this->getPrimaryKeys(), $class);
        }

        if ($this->findModel instanceof Closure) {
            if (!$model = call_user_func($this->findModel, $class, $condition, $this->primaryKeyParam)) {
                throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
            }
            return $model;
        }

        $query = call_user_func([$this->modelClass, 'find']);


        if (($model = $query->andWhere($condition)->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    protected function getRedirectUrl($model)
    {
        if ($this->redirect instanceof Closure) {
            return call_user_func($this->redirect, $model);
        }
        return $this->redirect;
    }

    public function redirect($model)
    {
        if (!$url = $this->getRedirectUrl($model)) {
            return $this->controller->refresh();
        }
        if (Yii::$app->request->isPjax) {
            return Yii::$app->response->redirect($url, 302, false);
        }
        return $this->controller->redirect($url);
    }
}